// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.12.4
// source: wearable_data.proto

package health_sync

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WearableDate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId     string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeviceType string `protobuf:"bytes,2,opt,name=device_type,json=deviceType,proto3" json:"device_type,omitempty"`
	Rousume    string `protobuf:"bytes,3,opt,name=rousume,proto3" json:"rousume,omitempty"`
	Date       string `protobuf:"bytes,4,opt,name=date,proto3" json:"date,omitempty"`
}

func (x *WearableDate) Reset() {
	*x = WearableDate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wearable_data_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WearableDate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WearableDate) ProtoMessage() {}

func (x *WearableDate) ProtoReflect() protoreflect.Message {
	mi := &file_wearable_data_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WearableDate.ProtoReflect.Descriptor instead.
func (*WearableDate) Descriptor() ([]byte, []int) {
	return file_wearable_data_proto_rawDescGZIP(), []int{0}
}

func (x *WearableDate) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *WearableDate) GetDeviceType() string {
	if x != nil {
		return x.DeviceType
	}
	return ""
}

func (x *WearableDate) GetRousume() string {
	if x != nil {
		return x.Rousume
	}
	return ""
}

func (x *WearableDate) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

var File_wearable_data_proto protoreflect.FileDescriptor

var file_wearable_data_proto_rawDesc = []byte{
	0x0a, 0x13, 0x77, 0x65, 0x61, 0x72, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x5f, 0x73, 0x79,
	0x6e, 0x63, 0x1a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x76, 0x0a, 0x0c, 0x57, 0x65, 0x61, 0x72, 0x61, 0x62, 0x6c, 0x65, 0x44, 0x61, 0x74, 0x65,
	0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x64, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x6f,
	0x75, 0x73, 0x75, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x6f, 0x75,
	0x73, 0x75, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x32, 0x4f, 0x0a, 0x13, 0x57, 0x65, 0x61, 0x72,
	0x61, 0x62, 0x6c, 0x65, 0x44, 0x61, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x38, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x19, 0x2e, 0x68, 0x65, 0x61, 0x6c,
	0x74, 0x68, 0x5f, 0x73, 0x79, 0x6e, 0x63, 0x2e, 0x57, 0x65, 0x61, 0x72, 0x61, 0x62, 0x6c, 0x65,
	0x44, 0x61, 0x74, 0x65, 0x1a, 0x11, 0x2e, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x5f, 0x73, 0x79,
	0x6e, 0x63, 0x2e, 0x56, 0x6f, 0x69, 0x64, 0x22, 0x00, 0x42, 0x16, 0x5a, 0x14, 0x67, 0x65, 0x6e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x5f, 0x73, 0x79, 0x6e,
	0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_wearable_data_proto_rawDescOnce sync.Once
	file_wearable_data_proto_rawDescData = file_wearable_data_proto_rawDesc
)

func file_wearable_data_proto_rawDescGZIP() []byte {
	file_wearable_data_proto_rawDescOnce.Do(func() {
		file_wearable_data_proto_rawDescData = protoimpl.X.CompressGZIP(file_wearable_data_proto_rawDescData)
	})
	return file_wearable_data_proto_rawDescData
}

var file_wearable_data_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_wearable_data_proto_goTypes = []any{
	(*WearableDate)(nil), // 0: health_sync.WearableDate
	(*Void)(nil),         // 1: health_sync.Void
}
var file_wearable_data_proto_depIdxs = []int32{
	0, // 0: health_sync.WearableDateService.Create:input_type -> health_sync.WearableDate
	1, // 1: health_sync.WearableDateService.Create:output_type -> health_sync.Void
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_wearable_data_proto_init() }
func file_wearable_data_proto_init() {
	if File_wearable_data_proto != nil {
		return
	}
	file_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_wearable_data_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*WearableDate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_wearable_data_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wearable_data_proto_goTypes,
		DependencyIndexes: file_wearable_data_proto_depIdxs,
		MessageInfos:      file_wearable_data_proto_msgTypes,
	}.Build()
	File_wearable_data_proto = out.File
	file_wearable_data_proto_rawDesc = nil
	file_wearable_data_proto_goTypes = nil
	file_wearable_data_proto_depIdxs = nil
}
